import { test, expect } from '@playwright/test';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { randomUUID } from 'node:crypto';
import path from 'node:path';
import sharp from 'sharp';
import { cleanupWorkspaces } from './asset-test-utils.cjs';
import { cleanupMail } from './mailhog-utils.cjs';

test('administrator command, analytics, user editing, board preview, guest transfer and role isolation', async ({ page, context, browser }) => {
  test.setTimeout(120000);
  const email = `admin-ui-${randomUUID()}@example.test`;
  const userEmail = `managed-ui-${randomUUID()}@example.test`;
  const password = 'Admin-browser-password-123';
  const newPassword = 'Managed-browser-password-456';
  const owners: string[] = [];
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('dialog', (dialog) => dialog.accept());
  const guest = await browser.newContext({ baseURL: 'http://localhost:5174' });
  const ordinary = await browser.newContext({ baseURL: 'http://localhost:5174' });
  try {
    await promisify(execFile)(process.execPath, ['--env-file=.env', 'scripts/create-admin.cjs', '--email', email, '--name', 'Тестовый администратор'], {
      cwd: path.resolve('apps/server'), env: { ...process.env, ADMIN_PASSWORD: password },
    });
    const login = await context.request.post('/api/auth/login', { data: { email, password } });
    expect(login.ok()).toBeTruthy();
    const admin = await login.json();
    owners.push(admin.workspaceId);
    expect(admin.user.role).toBe('admin');
    const created = await context.request.post('/api/admin/users', { data: { email: userEmail, name: 'Тестовый пользователь', password } });
    expect(created.ok()).toBeTruthy();
    const users = await (await context.request.get(`/api/admin/users?search=${encodeURIComponent(userEmail)}`)).json();
    owners.push(users.items[0].workspaceId);
    const guestInfo = await (await guest.request.post('/api/auth/guest')).json();
    owners.push(guestInfo.workspaceId);
    const board = await (await guest.request.post('/api/boards', { data: { title: 'Доска для админ-панели' } })).json();
    const png = await sharp({ create: { width: 240, height: 120, channels: 3, background: '#3b82f6' } }).png().toBuffer();
    const asset = await (await guest.request.post('/api/assets', { multipart: { file: { name: 'board.png', mimeType: 'image/png', buffer: png } } })).json();
    expect((await guest.request.put(`/api/boards/${board.id}`, { data: { title: board.title, revision: 0, document: { version: 1, background: { pattern: 'grid', size: 32 }, elements: [{ id: randomUUID(), kind: 'image', assetId: asset.id, x: 60, y: 70, width: 240, height: 120 }] } } })).ok()).toBeTruthy();
    await page.goto('/admin');
    await expect(page.getByRole('heading', { name: 'Обзор', exact: true })).toBeVisible();
    await expect(page.getByText('Как растёт BluviBoard', { exact: true })).toBeVisible();
    await expect(page.locator('.admin-stat')).toHaveCount(4);
    await expect(page.locator('.recharts-wrapper > svg.recharts-surface')).toHaveCount(1);
    await page.screenshot({ path: 'test-results/admin-dashboard.png', fullPage: true });
    const nav = page.getByRole('navigation', { name: 'Разделы админ-панели' });
    await nav.getByRole('button', { name: 'Пользователи', exact: true }).click();
    let row = page.getByRole('row').filter({ hasText: userEmail });
    await row.getByRole('button', { name: 'Изменить Тестовый пользователь', exact: true }).click();
    const userDialog = page.getByRole('dialog', { name: 'Управление пользователем' });
    await userDialog.getByLabel('Имя', { exact: true }).fill('Имя после изменения');
    await userDialog.getByLabel('Новый пароль (необязательно)', { exact: false }).fill(newPassword);
    await userDialog.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(userDialog).toHaveCount(0);
    row = page.getByRole('row').filter({ hasText: userEmail });
    await expect(row).toContainText('Имя после изменения');
    await row.getByRole('button', { name: 'Заблокировать Имя после изменения', exact: true }).click();
    await expect(row).toContainText('Заблокирован');
    await row.getByRole('button', { name: 'Разблокировать Имя после изменения', exact: true }).click();
    await expect(row).toContainText('Активен');
    await row.getByRole('button', { name: 'Изменить Имя после изменения', exact: true }).click();
    const roleDialog = page.getByRole('dialog', { name: 'Управление пользователем' });
    await roleDialog.getByRole('combobox', { name: 'Роль пользователя' }).selectOption('admin');
    await roleDialog.getByLabel('Ваш пароль для смены роли', { exact: false }).fill(password);
    await roleDialog.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(roleDialog).toHaveCount(0);
    await expect(row.getByText('Администратор', { exact: true })).toBeVisible();
    await row.getByRole('button', { name: 'Изменить Имя после изменения', exact: true }).click();
    await roleDialog.getByRole('combobox', { name: 'Роль пользователя' }).selectOption('user');
    await roleDialog.getByLabel('Ваш пароль для смены роли', { exact: false }).fill(password);
    await roleDialog.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(roleDialog).toHaveCount(0);
    await expect(row.getByText('Пользователь', { exact: true })).toBeVisible();
    await nav.getByRole('button', { name: 'Доски', exact: true }).click();
    await page.getByRole('button', { name: 'Открыть Доска для админ-панели', exact: true }).click();
    const preview = page.getByRole('dialog', { name: 'Просмотр доски', exact: true });
    await expect.poll(() => preview.locator('canvas').first().evaluate((element) => {
      const canvas = element as HTMLCanvasElement;
      const pixels = canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data;
      return pixels.some((value, index) => index % 4 === 0 && value === 59 && pixels[index + 1] === 130 && pixels[index + 2] === 246);
    })).toBe(true);
    await preview.getByLabel('Название доски', { exact: true }).fill('Переименовано администратором');
    await preview.getByRole('button', { name: 'Сохранить', exact: true }).click();
    await expect(preview).toHaveCount(0);
    await expect(page.getByRole('row').filter({ hasText: 'Переименовано администратором' })).toBeVisible();
    await page.screenshot({ path: 'test-results/admin-boards.png', fullPage: true });
    await nav.getByRole('button', { name: 'Гости', exact: true }).click();
    await page.getByRole('row').filter({ hasText: guestInfo.workspaceId }).getByRole('button', { name: 'Передать доски аккаунту' }).click();
    const transfer = page.getByRole('dialog', { name: 'Передача гостевых досок' });
    await transfer.getByLabel('Почта аккаунта-получателя').fill(userEmail);
    await transfer.getByRole('button', { name: 'Передать доски', exact: true }).click();
    await expect(transfer).toHaveCount(0);
    expect((await guest.request.get('/api/boards')).status()).toBe(401);
    const normalLogin = await ordinary.request.post('/api/auth/login', { data: { email: userEmail, password: newPassword } });
    expect(normalLogin.ok()).toBeTruthy();
    expect((await ordinary.request.get('/api/admin/overview')).status()).toBe(403);
    expect((await ordinary.request.get(`/api/assets/${asset.id}`)).status()).toBe(200);
    const deniedPage = await ordinary.newPage();
    await deniedPage.goto('/admin');
    await expect(deniedPage.getByRole('heading', { name: 'Вход в админ-панель', exact: true })).toBeVisible();
    await expect(deniedPage.getByRole('button', { name: 'Регистрация', exact: true })).toHaveCount(0);
    await expect(deniedPage.getByRole('button', { name: 'Продолжить как гость', exact: true })).toHaveCount(0);
    await expect(deniedPage.getByRole('button', { name: 'Забыли пароль?', exact: true })).toHaveCount(0);
    await nav.getByRole('button', { name: 'Журнал действий', exact: true }).click();
    await expect(page.getByRole('cell', { name: 'Доски гостя переданы аккаунту', exact: true })).toBeVisible();
    await nav.getByRole('button', { name: 'Почта', exact: true }).click();
    await page.getByLabel('Почта получателя').fill(email);
    await page.getByRole('button', { name: 'Отправить тестовое письмо', exact: true }).click();
    await expect(page.getByRole('status')).toContainText('Тестовое письмо отправлено');
    await page.getByRole('button', { name: 'Вернуться к доскам', exact: true }).click();
    await expect(page.getByRole('button', { name: 'Админ-панель →', exact: true })).toBeVisible();
    expect(errors).toEqual([]);
  } finally {
    await guest.close(); await ordinary.close();
    await cleanupWorkspaces(owners, process.env.BB_E2E_IMAGE_DIRECTORY);
    await cleanupMail(email);
  }
});
