server {
    listen 80;
    listen [::]:80;
    server_name bluviboard.ru;
    location ^~ /.well-known/acme-challenge/ { root /var/lib/bluviboard/acme; }
    location / { return 301 https://bluviboard.ru$request_uri; }
}
